export const LANG_KEY_CONST = {
  AUTH: {
    LOGIN_TITLE: "auth_login_title",
    LOGIN_SUBTITLE: "auth_login_subtitle",
    LOGIN_INPUT_EMAIL: "auth_login_input_email",
    LOGIN_INPUT_PLACE_EMAIL: "auth_login_input_place_email",
    LOGIN_INPUT_PASSWORD: "auth_login_input_password",
    LOGIN_INPUT_PLACE_PASSWORD: "auth_login_input_place_password",
    LOGIN_BTN_LOGIN: "auth_login_btn_login",
    LOGIN_CKCBOX_REMEMBER: "auth_login_ckcbox_remember",
  },
  EXPORT: "export",
  SELECT_ALL: "select_all",
  PERMISSION: {
    BTN_ADD: "permission_btn_add",
  },
  TOOLTIP_FILTER: "tooltip_filter",
  TOOLTIP_SORT: "tooltip_sort",
  TOOLTIP_INPUT_DATE: "tooltip_input_date",
  TOOLTIP_INPUT_DATE_RANGE: "tooltip_input_date_range",
  TOOLTIP_MANAGE_COLUMN: "tooltip_manage_column",
  TOOLTIP_REFRESH: "tooltip_refresh",
  FILTER: "filter",
  SORT: "sort",
  EMPTY_TABLE_LIST: "empty_table_list",
  SHOWING: "showing",
  TO: "to",
  OF: "of",
  GO_TO_PAGE: "go_to_page",
  TOOLTIP_GO_TO_PAGE: "tooltip_go_to_page",
  INPUT_GO_TO_PAGE: "input_go_to_page",
  ENTRIES: "entries",
};
