export const LANG_KEY_CONST = {
  AUTH_LOGIN_TITLE: "auth_login_title",
  AUTH_LOGIN_SUBTITLE: "auth_login_subtitle",
  AUTH_LOGIN_INPUT_EMAIL: "auth_login_input_email",
  AUTH_LOGIN_INPUT_EMAIL_PLACEHOLDER: "auth_login_input_email_placeholder",
  AUTH_LOGIN_INPUT_PASSWORD: "auth_login_input_password",
  AUTH_LOGIN_INPUT_PASSWORD_PLACEHOLDER:
    "auth_login_input_password_placeholder",
  AUTH_LOGIN_BTN_LOGIN: "auth_login_btn_login",
  AUTH_LOGIN_CKCBOX_LOGIN: "auth_login_ckcbox_login",
  AUTH_LOGIN_TOAST_LOGIN_SUCCESS: "auth_login_toast_login_success",

  PERMISSION_TITLE: "permission_title",
  PERMISSION_FIELD_RESOURCE: "permission_field_resource",
  PERMISSION_FIELD_ACTION: "permission_field_action",
  PERMISSION_FIELD_DESCRIPTION: "permission_field_description",
  PERMISSION_FIELD_PATH: "permission_field_path",

  UNIT_TITLE_ADD: "unit_title_add",
  UNIT_TITLE_UPDATE: "unit_title_update",
  UNIT_FIELD_NAME: "unit_field_name",
  UNIT_FIELD_CODE: "unit_field_code",
  UNIT_FIELD_DESCRIPTION: "unit_field_description",
  UNIT_INPUT_NAME_TITLE: "unit_input_name_title",
  UNIT_INPUT_NAME_PLACEHOLDER: "unit_input_name_placeholder",
  UNIT_INPUT_CODE_TITLE: "unit_input_code_title",
  UNIT_INPUT_CODE_PLACEHOLDER: "unit_input_code_placeholder",
  UNIT_INPUT_DESCRIPTION_TITLE: "unit_input_description_title",
  UNIT_INPUT_DESCRIPTION_PLACEHOLDER: "unit_input_description_placeholder",

  ROLE_TITLE_ADD: "role_title_add",
  ROLE_TITLE_UPDATE: "role_title_update",
  ROLE_BTN_ADD: "role_btn_add",
  ROLE_INPUT_NAME_TITLE: "role_input_name_title",
  ROLE_INPUT_NAME_PLACEHOLDER: "role_input_name_placeholder",
  ROLE_INPUT_DESCRIPTION_TITLE: "role_input_description_title",
  ROLE_INPUT_DESCRIPTION_PLACEHOLDER: "role_input_description_placeholder",

  FORM_ERR_NOT_EMPTY: "form_err_not_empty",
  FORM_ERR_MAX_LENGTH: "form_err_max_length",

  COMMON_BTN_EXPORT: "common_btn_export",
  COMMON_BTN_SELECT_ALL: "common_btn_select_all",
  COMMON_TOOLTIP_FILTER: "common_tooltip_filter",
  COMMON_TOOLTIP_SORT: "common_tooltip_sort",
  COMMON_TOOLTIP_INPUT_DATE: "common_tooltip_input_date",
  COMMON_TOOLTIP_INPUT_DATE_RANGE: "common_tooltip_input_date_range",
  COMMON_TOOLTIP_MANAGE_COLUMN: "common_tooltip_manage_column",
  COMMON_TOOLTIP_REFRESH: "common_tooltip_refresh",
  COMMON_FILTER: "common_filter",
  COMMON_SORT: "common_sort",
  COMMON_ASC: "common_asc",
  COMMON_DESC: "common_desc",
  COMMON_LOGOUT: "common_logout",
  COMMON_PROCESSING: "common_processing",
  COMMON_APPLY_FILTER: "common_apply_filter",
  COMMON_CANCEL: "common_cancel",
  COMMON_SEARCH: "common_search",
  COMMON_ORDER: "common_order",
  COMMON_CREATED_AT: "common_created_at",
  COMMON_FIELD: "common_field",
  COMMON_MORE: "common_more",
  COMMON_EDIT: "common_edit",
  COMMON_ADD: "common_add",
  COMMON_SAVE: "common_save",
  COMMON_CREATE: "common_create",
  COMMON_SELECTED: "common_selected",
  COMMON_CREATE_SUCCESS: "common_create_success",
  COMMON_SAVE_SUCCESS: "common_save_success",
  COMMON_DELETE_SUCCESS: "common_delete_success",

  TABLE_LIST_EMPTY: "table_list_empty",
  TABLE_OF: "table_of",
  TABLE_EXPORT_PAGE: "table_export_page",
  TABLE_EXPORT_ALL: "table_export_all",
  TABLE_GO_TO_PAGE: "table_go_to_page",
  TABLE_TOOLTIP_GO_TO_PAGE: "table_tooltip_go_to_page",
  TABLE_INPUT_GO_TO_PAGE_PLACEHOLDER: "table_input_go_to_page_placeholder",

  MENU_RBAC: "menu_rbac",
  MENU_RBAC_PERMISSION: "menu_rbac_permission",
  MENU_RBAC_ROLE: "menu_rbac_role",
  MENU_RBAC_USER: "menu_rbac_user",
  MENU_SETTING: "menu_setting",
  MENU_SETTING_LANG: "menu_setting_lang",
  MENU_DASHBOARD: "menu_dashboard",
  MENU_INVENTORY_MANAGEMENT: "menu_inventory_management",
  MENU_INVENTORY_MANAGEMENT_UNIT: "menu_inventory_management_unit",
  MENU_INVENTORY_MANAGEMENT_CATEGORY: "menu_inventory_management_category",

  PERMISSION: "permission",
  LANG: "lang",
  USER: "user",
  CATEGORY: "category",
  UNIT: "unit",
};
